### ISSUE TITLE
Missing messageTypes.js for receiver.html

### ISSUE THREAD

**Issue by timehat** [pjjanak/chromecast-hello-world#1]
First off--thanks for creating this project.  Very helpful to see in one place how to get the basics going.

I'm not sure if you just forgot to include the messageTypes.js file for the receiver app, or if it's not necessary (or if it should be acquired elsewhere, or is provided by the Chromecast device somehow).

I was having issues and removed the reference to it and things seem to be fine, but since I'm ignorant of if it's something special that should be there, I didn't feel a pull request to remove the reference was in order.

**Comment by pjjanak** [comment]
Glad you found it helpful! That reference shouldn't be in there...this project was a simplification of something else I'm working on and I guess I forgot to remove that...thanks for finding that. I'm pushing a fix now!
