### ISSUE TITLE
Thank you so much

### ISSUE THREAD

**Issue by ghost** [pjjanak/chromecast-hello-world#2]
Not an issue, just wanted to say thanks a ton for breaking this down way better than Google.  Really appreciate it, dude!

**Comment by zoharbabin** [comment]
:+1:  Google should upgrade their docs and samples according to this.

**Comment by slm4996** [comment]
Agreed! googles examples and demo code, with the exception of TicTacToe, center on media only. I realize this is a developer preview SDK so I can't really complain to google so your mini tutorial really helped me wrap my head around the API.
